### ISSUE TITLE
CORS react client

### ISSUE THREAD

**Issue by alcalawil** [alancampora/argentina-covid19-data#1]
Hola, estoy intentando consumirla desde React y me da un cors error
![image](https://user-images.githubusercontent.com/29496102/78460712-77c9a900-7699-11ea-9b4c-ddb860a43580.png)

No estoy seguro si tienes que cambiar los cors en la api o soy yo tengo que poner algun header

PD: gracias por esta api

**Comment by alancampora** [comment]
Buenas! Pudiste hacerlo andar ? Ahora me fijo si hay alguna config que tenga que agregar de mi lado

**Comment by alancampora** [comment]
Acabo de hacer un cambio en la api! Fijate si ahora funciona, no deberías agregar nada de tu lado. Avisame

**Comment by alcalawil** [comment]
Ahora sí todo bien.. Gracias!!

**Comment by alancampora** [comment]
De nada! Gracias por avisarme!
