### ISSUE TITLE
Error en los datos

### ISSUE THREAD

**Issue by alcalawil** [alancampora/argentina-covid19-data#2]
Hola.. Estos campos están arrojando valores que no son los correctos.
![image](https://user-images.githubusercontent.com/29496102/79559682-90b06200-807c-11ea-9e44-bf7648dd79c2.png)

Fui a wikipedia y está todo bien, puede ser que hayan cambiado el orden de algunas cosas

**Comment by alancampora** [comment]
Hola @alcalawil gracias por reportar el error! Te acordas cual es el dia que estaba fallando? Busque esos valores y no pude encontrarlos

**Comment by alcalawil** [comment]
@alancampora fue solo ayer, los demás días la estuve usando y anduvo todo bien. Si te das cuenta, `new_cases` y `new_deaths` mostraban los valores que debían mostrarse en `total_`.. Yo solucioné temporalmente invirtiendo esos valores, y después el `total_deaths` no sé de donde lo sacaba

**Comment by alcalawil** [comment]
Igual con el fix que subiste ayer se arregló enseguida

**Comment by alancampora** [comment]
Genial! Lo que sucede es que cada tanto cambian el nombre de alguna columna y rompen la API, me tengo que fijar como hacerla un poco mas estable.
Gracias por avisarme!

**Comment by alcalawil** [comment]
Bien!

Aprovecho y te dejo la url y el repo de donde estoy consumiendo esta api

https://coronabaires.info/
https://github.com/alcalawil/coronabaires
